/**
 * Build script for Lexical Editor WebView bundle
 *
 * This script bundles the Lexical editor code into a single JS file
 * that can be embedded in the WebView HTML.
 *
 * Usage: node build.mjs
 */
import * as esbuild from "esbuild";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function build() {
  console.log("Building Lexical editor bundle...");

  try {
    const result = await esbuild.build({
      entryPoints: [path.join(__dirname, "lexical-editor.tsx")],
      bundle: true,
      minify: true,
      format: "iife",
      target: ["es2020"],
      write: false,
      loader: {
        ".tsx": "tsx",
        ".ts": "ts",
      },
    });

    const bundleCode = result.outputFiles[0].text;

    // Read the HTML template
    const htmlTemplate = fs.readFileSync(path.join(__dirname, "editor-template.html"), "utf-8");

    // Replace placeholder with bundle
    const finalHtml = htmlTemplate.replace("/* BUNDLE_PLACEHOLDER */", bundleCode);

    // Write the final editor-html.ts file
    const outputContent = `/**
 * Auto-generated Lexical Editor HTML
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the source files in the web/ directory and run the build script.
 *
 * Generated at: ${new Date().toISOString()}
 */
export const EDITOR_HTML = ${JSON.stringify(finalHtml)};
`;

    fs.writeFileSync(path.join(__dirname, "..", "editor-html.ts"), outputContent, "utf-8");

    console.log("Bundle built successfully!");
    console.log(`Bundle size: ${(bundleCode.length / 1024).toFixed(2)} KB`);
  } catch (error) {
    console.error("Build failed:", error);
    process.exit(1);
  }
}

build();
